### ISSUE TITLE
Can you share the COLMAP parameters or tricks for getting good initial poses in egocentric images? 

### ISSUE THREAD

**Issue by coreqode** [dichotomies/NeuralDiff#2]
I am using the SIMPLE_RADIAL camera model and exhaustive as feature matching. But bundle adjustment does not converge and gives the warning of "no image pair found"

**Comment by dichotomies** [comment]
Hi, I remember having the same problem initially with COLMAP.  It's not trivial to get good reconstructions from ego-centric videos. The most important COLMAP parameters/tricks that helped in our case are:
1. Create masks that cover the person in your ego-centric videos (see supplementary material, Figure 7). The COLMAP option for that is `--ImageReader.mask_path` (when using the feature extractor). Otherwise the features detected on the person can distort the reconstruction.
2. Use the `vocab_tree_matcher` instead of the exhaustive feature matcher. There, you have to also choose the appropriate dictionary (depending on the number of frames that you want to use for COLMAP). **This is especially important for the "no image pair found" issue.**
3. Extracting multiple models and then choosing the largest one might help. You can select this option in the mapper via `Mapper.multiple_models`.

**Comment by coreqode** [comment]
Thanks a lot for the pointers. 
One doubt I had was how do you validate the camera poses generated from the COLMAP? Do you calculate some type of reprojection error?

**Comment by dichotomies** [comment]
Indeed, COLMAP calculates a reprojection error. I would recommend looking at the [COLMAP GUI](https://colmap.github.io/gui.html). I found the point clouds to provide quite valuable feedback about how well the reconstruction went.

**Comment by coreqode** [comment]
Thanks a lot.
