### ISSUE TITLE
Getting good results on own dataset

### ISSUE THREAD

**Issue by ChikaYan** [dichotomies/NeuralDiff#3]
Hi and thank you very much for your amazing work!
I tried to run the code on some video sequences (not exactly egocentric but similar), however the quality is not as good compared to the EPIC-kitchen dataset. Here's how it looks like:
![figure](https://user-images.githubusercontent.com/32335747/164909082-252bcb85-2910-4f79-8feb-f4ce6f71c747.gif)
May I ask if you could share a few tricks on how to get better results? Also, I'm concerned if I managed to process the camera parameters correctly, so it would be great if you can share the preprocessing code that converts COLMAP data into the desired poses (I'm not sure if any coordinate system transfer or re-scaling is required).
Many thanks in advance!

Update: I ran with more epoches (50 instead of 10) considering I have less frames (100) in total. The results are less blurry, but the decomposition still fails. Do you think this is expected?
![figure](https://user-images.githubusercontent.com/32335747/165073094-82965cff-bd80-4493-a2a6-2e7f8c8f6076.gif)

**Comment by dichotomies** [comment]
Hi, I'm glad to see you've made it work for your own dataset!

Yea makes sense regarding the COLMAP conversion. I've received some requests for that and will release the code for converting COLMAP datasets into our format in the next days.

Some thoughts on the results: 
1. Have you adjusted the transient embedding dimensionality? The default value is 1000 (our scenes have mostly 800 to 1000 frames), but in your you should adjust it to 100.
2. The actor model won't be helpful here since the person is barely visible (in EPIC-Kitchens, it's helpful since the person is occluding the scene quite often). I would recommend disabling the actor in this case. Also, since the viewpoints don't change as heavily as in EPIC-Kitchens, the actor might rather confuse the overall model since it tries to capture something that doesn't exist. A similar problem would occur if you would enable the actor model on static scenes (e.g. classic NeRF scenes like 'trex'). 
3. The object that you try to segment is significantly less "semi-static" than what our model would expect, because it's moving most of the time (being thrown, then rolling on the table). Therefore, the model has difficulty segmenting it. In comparison, the EPIC-Kitchens data has mostly objects that are moved very briefly and then stay static for most of the time (hence, semi-static).
4. If it's a self-made video and you can create another one, I would try out setting up a more semi-static scenario: take an object from one place, and place it to another one. Make sure to cover both states for some time.

Hope some of that helps you and feel free to get back to me if you have further questions.

**Comment by ChikaYan** [comment]
Thank you very much! Would be really helpful to have the COLMAP converting code.
May I double-check that for bullet point 1, I should change the value of `--N_vocab`?

A follow up: I changed `--N_vocab` to 100 and disabled the actor component by adding a new parameters `--suppress_person` to `train.py`. However the results appear even worse:
![figures](https://user-images.githubusercontent.com/32335747/166261667-376fe681-fb07-4413-99fa-c844e4eab03f.gif)


I used the pose recentering code from original NeRF to preprocess the pose from COLMAP.

I'm really confused that, even though the decomposition target is probably more dynamic and therefore difficult to learn and segment, why would the model perform so badly on even the static background of the scene? As you can see, the majority of the objects in the video remain perfectly still throughout the whole time. Even for the part that it managed to segment correctly (i.e., the floor and the wall) the reconstruction appears very blurry.

Follow up 2: I tried a synthetic data with ground truth camera, as well as some test views on a frozen time frame. Here's the result:
![ezgif-5-fb13c24302](https://user-images.githubusercontent.com/32335747/165938857-d2f60f89-efcd-4f04-ab87-21d53b7532ff.gif)
It successfully reconstructs high quality training views (although decomposition still fails, and I'm not sure why static component can learn such high quality dynamic object), but the novel view seems really weird (sample 200~300). Do you think this is an issue with camera pose or overfitted static component?

**Comment by dichotomies** [comment]
Hi, the COLMAP converter is now ready to use, see the README. Hope this is going to help, but feel free to get in touch if you have further questions!
